apiVersion: v1
kind: Secret
metadata:
  name: kumari-k8s-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/themilton/kumari-k8s-manifests.git
  username: resham
  password: <sealed-secret-ref>  # More on this later
